name: Scheduled Discord DM

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}   # ← これを足す！

jobs:
  send_dm:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - uses: actions/checkout@v4

      # Python 環境をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 依存ライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py

      # main.py を実行してDM送信
      - name: Send scheduled DM
        env:
          DISCORD_TOKEN:     ${{ secrets.DISCORD_TOKEN }}
          DISCORD_TARGET_ID: ${{ secrets.DISCORD_TARGET_ID }}
        run: python main.py
